image: gradle:jdk17

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "10406996"

  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build
  - test
  - package

.install_android_sdk: &install_android_sdk
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -q -d android-sdk-linux android-sdk.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - echo y | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-${ANDROID_COMPILE_SDK}" > /dev/null
  - echo y | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
  - set +o pipefail
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
  - set -o pipefail

.configure_artifactory: &configure_artifactory
  - echo $ARTIFACTORY_USER >> gradle.properties
  - echo $ARTIFACTORY_PASSWORD >> gradle.properties
  - echo $ARTIFACTORY_URL >> gradle.properties

.configure_release: &configure_release
  - echo $RELEASE_STORE_FILE >> gradle.properties
  - echo $RELEASE_STORE_PASSWORD >> gradle.properties
  - echo $RELEASE_KEY_ALIAS >> gradle.properties
  - echo $RELEASE_KEY_PASSWORD >> gradle.properties

# BUILD
build_debug:
  before_script:
    - *configure_artifactory
    - *configure_release
    - *install_android_sdk
  stage: build
  except:
    - main
  script:
    - ./gradlew assembleDebug -PcachePush=true
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk

build_release:
  before_script:
    - *configure_artifactory
    - *configure_release
    - *install_android_sdk
  stage: build
  only:
    - main
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ./gradlew assembleRelease -PcachePush=true
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk

# TEST
unit_test_debug:
  before_script:
    - *configure_artifactory
    - *configure_release
    - *install_android_sdk
  stage: test
  except:
    - main
  script:
    - ./gradlew testDebugUnitTest

unit_test_release:
  before_script:
    - *configure_artifactory
    - *configure_release
    - *install_android_sdk
  stage: test
  only:
    - main
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ./gradlew testReleaseUnitTest

# PACKAGE
.package_template: &package_template
  before_script:
    - export VERSION_NAME=`egrep '^[[:blank:]]+versionName[[:blank:]]'  app/build.gradle.kts | awk '{print $3}' | sed s/\"//g`
    - export VERSION_CODE=`egrep '^[[:blank:]]+versionCode[[:blank:]]'  app/build.gradle.kts | awk '{print $3}'`
    - mkdir -p deliverables

    # Log build info
    - touch ./deliverables/info.txt
    - echo "Build date          $(date)"                >> ./deliverables/info.txt
    - echo "App version name    ${VERSION_NAME}"        >> ./deliverables/info.txt
    - echo "App version code    ${VERSION_CODE}"        >> ./deliverables/info.txt
    - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> ./deliverables/info.txt
    - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./deliverables/info.txt
    - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./deliverables/info.txt

package_nightly:
  <<: *package_template
  stage: package
  environment: Development
  only:
    - develop
  script:
    - mv app/build/outputs/apk/debug/app-debug.apk ./deliverables/Cadenas-v$VERSION_NAME-$VERSION_CODE-debug.apk
  artifacts:
    expire_in: 3 days
    paths:
      - deliverables

package_release:
  <<: *package_template
  stage: package
  environment: Release
  only:
    - main
  script:
    - mv app/build/outputs/apk/release/app-release.apk ./deliverables/Cadenas-v$VERSION_NAME-$VERSION_CODE-release.apk
  artifacts:
    expire_in: 4 weeks
    paths:
      - deliverables